// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNr4hlNLaEMmBMPYIImxYcjl6egalfwkE',
    appId: '1:28662539360:web:e96cd0d0bdb67b13b84f05',
    messagingSenderId: '28662539360',
    projectId: 'marusinecapp-81e2e',
    authDomain: 'marusinecapp-81e2e.firebaseapp.com',
    storageBucket: 'marusinecapp-81e2e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOilxoxJLYKuowmkiTCYra-KtH8GseMgg',
    appId: '1:28662539360:android:de82e3d2acbba81bb84f05',
    messagingSenderId: '28662539360',
    projectId: 'marusinecapp-81e2e',
    storageBucket: 'marusinecapp-81e2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0UyCvzFACI9vb1rDkZsQs6aM_5H4CBN4',
    appId: '1:28662539360:ios:28271691eed2a7bcb84f05',
    messagingSenderId: '28662539360',
    projectId: 'marusinecapp-81e2e',
    storageBucket: 'marusinecapp-81e2e.appspot.com',
    iosBundleId: 'com.example.marusinecApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0UyCvzFACI9vb1rDkZsQs6aM_5H4CBN4',
    appId: '1:28662539360:ios:ab030bc774ade62fb84f05',
    messagingSenderId: '28662539360',
    projectId: 'marusinecapp-81e2e',
    storageBucket: 'marusinecapp-81e2e.appspot.com',
    iosBundleId: 'com.example.marusinecApp.RunnerTests',
  );
}
